### PR TITLE
update diverging import style introduced to keep coherent with current

### PR DESCRIPTION
**Pull request by mvesin**
practice

**PR description**

Very partial #1060 to cover only the newly introduced `imports` that diverge from current "majority" import style

**Developer Certificate Of Origin (DCO)**

By opening this merge request, you agree to the
[Developer Certificate of Origin (DCO)](https://github.com/fedbiomed/fedbiomed/blob/master/CONTRIBUTING.md#fed-biomed-developer-certificate-of-origin-dco)

This DCO essentially means that:

- you offer the changes under the same license agreement as the project, and
- you have the right to do that,
- you did not steal somebody else’s work.

**License**

Project code files should begin with these comment lines to help trace their origin:
```
# This file is originally part of Fed-BioMed
# SPDX-License-Identifier: Apache-2.0
```

Code files can be reused from another project with a compatible non-contaminating license.
They shall retain the original license and copyright mentions.
The `CREDIT.md` file and `credit/` directory shall be completed and updated accordingly.

**Guidelines for PR review**

General:

* give a glance to [DoD](https://fedbiomed.org/latest/developer/definition-of-done/)
* check [coding rules and coding style](https://fedbiomed.org/latest/developer/usage_and_tools/#coding-style)
* check docstrings (eg run `tests/docstrings/check_docstrings`)

Specific to some cases:

* update all conda envs consistently (`development` and `vpn`, Linux and MacOS)
* if modified researcher (eg new attributes in classes) check if breakpoint needs update (`breakpoint`/`load_breakpoint` in `Experiment()`, `save_state_breakpoint`/`load_state_breakpoint` in aggregators, strategies, secagg, etc.)
* if modified a component with versioning (config files, breakpoint, messaging protocol) then update the version following the rules in `common/utils/_versions.py`

### CODE REVIEW

**Comment by srcansiz** [comment]
Hi @mvesin, 

Thank you for the PR. I think the order of the import should be: 

1 - builtins 
2 - third party
3 - from library source (from fedbiomed)
4 - and from module directory like `from ._module` 

I've seen that there are some import from module directory amoig imports from fedbiomed module in general.

**Comment by mvesin** [comment]
> I've seen that there are some import from module directory among the import statements from fedbiomed in general.

Good point, thank you @srcansiz => I'm gonna update it in the PR + mention it in #1060

**Comment by mvesin** [comment]
hi @srcansiz I checked/updated import order for refactored files (`fedbiomed.researcher.federated_workflows`) as you requested + removed a few unused imports

**Comment by srcansiz** [comment]
> hi @srcansiz I checked/updated import order for refactored files (`fedbiomed.researcher.federated_workflows`) as you requested + removed a few unused imports

Thank you @mvesin. I am going to merge it.

**Pull request merged**
