### PR TITLE
Removes MP-SPDZ and related modules

### PR DESCRIPTION
**Pull request by srcansiz**
**PR description**

- Removes MPC controller module
- Removes some certificate manager methods specific to MP-SPDZ
- Removes 'mpspdz' entry from configuration file
- removes related unit tests
- Creates new entry in configuration for 'ceritificates'. To convert mpspdz certificate to default component certificates
- Researcher server certificates is now under 'certificate' section, not under 'server'
- Convert certificate registration to generic registration, however it is not in used.
- Updates documentation: removes or updates mpspdz related docs

**Developer Certificate Of Origin (DCO)**

By opening this merge request, you agree to the
[Developer Certificate of Origin (DCO)](https://github.com/fedbiomed/fedbiomed/blob/master/CONTRIBUTING.md#fed-biomed-developer-certificate-of-origin-dco)

This DCO essentially means that:

- you offer the changes under the same license agreement as the project, and
- you have the right to do that,
- you did not steal somebody else’s work.

**License**

Project code files should begin with these comment lines to help trace their origin:
```
# This file is originally part of Fed-BioMed
# SPDX-License-Identifier: Apache-2.0
```

Code files can be reused from another project with a compatible non-contaminating license.
They shall retain the original license and copyright mentions.
The `CREDIT.md` file and `credit/` directory shall be completed and updated accordingly.

**Guidelines for PR review**

General:

* give a glance to [DoD](https://fedbiomed.org/latest/developer/definition-of-done/)
* check [coding rules and coding style](https://fedbiomed.org/latest/developer/usage_and_tools/#coding-style)
* check docstrings (eg run `tests/docstrings/check_docstrings`)

Specific to some cases:

* update all conda envs consistently (`development` and `vpn`, Linux and MacOS)
* if modified researcher (eg new attributes in classes) check if breakpoint needs update (`breakpoint`/`load_breakpoint` in `Experiment()`, `save_state_breakpoint`/`load_state_breakpoint` in aggregators, strategies, secagg, etc.)
* if modified a component with versioning (config files, breakpoint, messaging protocol) then update the version following the rules in `common/utils/_versions.py`

### CODE REVIEW

**Comment by mvesin** [comment]
hi @srcansiz in case you did not see it yet: the CI build of documentation is broken by the PR

**Comment by mvesin** [comment]
Thank you @srcansiz for this work !

There are still a few references to MP-SPDZ that maybe also need to be removed
- `credit/mp-spdz-license.txt` => remove the whole file ?
- `tutorials/security/secure-aggregation.ipynb`

Also the part regarding docker containers building has a few remaining references
- `envs/vpn/docker/{node,researcher}/build_files/Dockerfile`
- `envs/vpn/docker/researcher/entry_point.bash`
-  `envs/vpn/docker/docker-compose.yml` `envs/vpn/docker/docker-compose_run_node.yml`

Did you test building/launching containers to check it's still functional ?

BTW I:
- update `security-model.md`
- fixed a pre-existing typo SPDZ => SPDX in `CREDIT.md`
- fixed misc bugs introduced in in `clean_node.py` `clean_researcher.py`

**Comment by mvesin** [comment]
FYI tested unit tests, running secagg notebook with several scenarios, cleaning configurations => works fine.

**Comment by srcansiz** [comment]
> hi @srcansiz in case you did not see it yet: the CI build of documentation is broken by the PR

Hi @mvesin,

Yes I realized it. I am going to fix it as soon as possible.

**Comment by srcansiz** [comment]
> Thank you @srcansiz for this work !
> 
> There are still a few references to MP-SPDZ that maybe also need to be removed
> 
> * `credit/mp-spdz-license.txt` => remove the whole file ?
> * `tutorials/security/secure-aggregation.ipynb`
> 
> Also the part regarding docker containers building has a few remaining references
> 
> * `envs/vpn/docker/{node,researcher}/build_files/Dockerfile`
> * `envs/vpn/docker/researcher/entry_point.bash`
> * `envs/vpn/docker/docker-compose.yml` `envs/vpn/docker/docker-compose_run_node.yml`
> 
> Did you test building/launching containers to check it's still functional ?
> 
> BTW I:
> 
> * update `security-model.md`
> * fixed a pre-existing typo SPDZ => SPDX in `CREDIT.md`
> * fixed misc bugs introduced in in `clean_node.py` `clean_researcher.py`

Hi @mvesin, 

Thanks for the finding those remaining references. I cleared those out too, and tested building and running vpn containers. Everything seems fine.

**Comment by mvesin** [comment]
Great job @srcansiz 
I merged the PR
Have a nice day

**Pull request merged**
