### PR TITLE
add documentation on declearn optimizers

### PR DESCRIPTION
**Pull request by ybouilla**
**PR description**
 Related to issue #810 

The goal of this PR is twofold:
1. create tutorial and documentation about new `declearn` compatible optimizers
2. update former documentation, with the fact that training plan have been modified

The task is not simple, especially since we do have 2 scaffolds implementation, which have both pros and cons. Which one should we document? Plus, we have 2 definitions of `aggregator`: it can be either a way to aggregate model weights (`FedAverage` naming is inappropriate in my opinion) or the algorithm that deals with aggregation, and optimization (like our native `scaffold` implementation). 
Having 2 libraries (declearn and fedbiomed) needed for defining optimizers can be really confusing, and setting specific aggregation strategies through the use of optimizers too)

I tried my best to explain things.

**Open Questions**:
1. how to cope with native implementations of scaffold and fedprox: should we put a deprecated banner? 

**checks**:
- [ ] check that links is working
- [ ] check that all documentation of he website has been updated accordingly

**Reviewers**
It will be nice if the following reviewers take a look at the webpages, and see if explainations are clear enough

- [x] Fed-BioMed developer
- [x] declearn developer
- [x] epione researcher / fedbiomed user

**Developer Certificate Of Origin (DCO)**

By opening this merge request, you agree to the
[Developer Certificate of Origin (DCO)](https://github.com/fedbiomed/fedbiomed/blob/master/CONTRIBUTING.md#fed-biomed-developer-certificate-of-origin-dco)

This DCO essentially means that:

- you offer the changes under the same license agreement as the project, and
- you have the right to do that,
- you did not steal somebody else’s work.

**License**

Project code files should begin with these comment lines to help trace their origin:
```
# This file is originally part of Fed-BioMed
# SPDX-License-Identifier: Apache-2.0
```

Code files can be reused from another project with a compatible non-contaminating license.
They shall retain the original license and copyright mentions.
The `CREDIT.md` file and `credit/` directory shall be completed and updated accordingly.

**Guidelines for PR review**

General:

* give a glance to [DoD](https://fedbiomed.org/latest/developer/definition-of-done/)
* check [coding rules and coding style](https://fedbiomed.org/latest/developer/usage_and_tools/#coding-style)
* check docstrings (eg run `tests/docstrings/check_docstrings`)

Specific to some cases:

* update all conda envs consistently (`development` and `vpn`, Linux and MacOS)
* if modified researcher (eg new attributes in classes) check if breakpoint needs update (`breakpoint`/`load_breakpoint` in `Experiment()`, `save_state`/`load_state` in aggregators, strategies, secagg, etc.)
* if modified a component with versioning (config files, breakpoint, messaging protocol) then update the version following the rules in `common/utils/_versions.py`

### CODE REVIEW

**Comment by ybouilla** [comment]
Hi Paul, thanks for your reply! Any input is much appreciated, so just don't hesitate if you feel there is something badly explained!
Indeed, i forgot mentioning that `declearn` optimizer can also work with strings - instead of optimodule and regularizers objects. Do you have any ideas on how  to document that ? I was thinking on providing a table with all OptiModule available and their names. Do you have any table that explain that on declearn documentation website ?

**Review by sharkovsky — APPROVED** [review]

**Comment by ybouilla** [comment]
> Hi Paul, thanks for your reply! Any input is much appreciated, so just don't hesitate if you feel there is something badly explained! Indeed, i forgot mentioning that `declearn` optimizer can also work with strings - instead of optimodule and regularizers objects. Do you have any ideas on how to document that ? I was thinking on providing a table with all OptiModule available and their names. Do you have any table that explain that on declearn documentation website ?

Done (in last comit)

**Comment by pandrey-fr** [comment]
Hello @ybouilla,

Between the holidays and the need to wrap up things that Nathan was working on, I had to delay my effort in writing an extensive guide on our Optimizer, that mentions the Fed-BioMed integration and could be linked to in your documentation. I have gotten back at it last week, and I am happy to say that it is nearly finished, and it should be online by next week on our website!

As to your question, that I did not answer before: you may use (or document the use of) `declearn.optimizer.list_optim_modules()` and `declearn.optimizer.list_optim_regularizers()` to access a dict that exposes the `{name_string: class_constructor}` mapping of all registered plug-ins.

**Comment by ErwanDemairy** [comment]
Hello some links that seem to be broken:
- docs/tutorials/advanced/in-depth-experiment-configuration.ipynb"
	- `[`declearn` based `Optimizers`](../../user-guide/advanced-optimization)` -> `[`declearn` based `Optimizers`](../../../user-guide/advanced-optimization)` 
-   docs/tutorials/optimizers/01-fedopt-and-scaffold.ipynb
	- `[\\`Optimizer\\` section in the User Guide]()`
	- `[this tutorial]()`
	- `[PyTorch native optimizers]()`
	- `User Guide`]()`
	- typos: exterma, 
- advanced-optimization.md
	- `[Secure Aggregation]()`
- experiment.md
	- `[`declearn`'s `Optimizers`](./../advanced-optimization)` ` KO
	-  `[`fedbimed.common.optimizer.Optimizer`](../../developer/api/researcher/experiment/developer/api/common/optimizer/)`
		  typo : fedbimed au lieu de fedbiomed
	- `[please visit the following webpage](./../advanced-optimization)`

**Pull request merged**
