### PR TITLE
Fix jupyter notebook token authentication automatic

### PR DESCRIPTION
**Pull request by mvesin**
**PR description**

Address #1194

**Developer Certificate Of Origin (DCO)**

By opening this merge request, you agree to the
[Developer Certificate of Origin (DCO)](https://github.com/fedbiomed/fedbiomed/blob/master/CONTRIBUTING.md#fed-biomed-developer-certificate-of-origin-dco)

This DCO essentially means that:

- you offer the changes under the same license agreement as the project, and
- you have the right to do that,
- you did not steal somebody else’s work.

**License**

Project code files should begin with these comment lines to help trace their origin:
```
# This file is originally part of Fed-BioMed
# SPDX-License-Identifier: Apache-2.0
```

Code files can be reused from another project with a compatible non-contaminating license.
They shall retain the original license and copyright mentions.
The `CREDIT.md` file and `credit/` directory shall be completed and updated accordingly.

**Guidelines for PR review**

General:

* give a glance to [DoD](https://fedbiomed.org/latest/developer/definition-of-done/)
* check [coding rules and coding style](https://fedbiomed.org/latest/developer/usage_and_tools/#coding-style)
* check docstrings (eg run `tests/docstrings/check_docstrings`)

Specific to some cases:

* update all conda envs consistently (`development` and `vpn`, Linux and MacOS)
* if modified researcher (eg new attributes in classes) check if breakpoint needs update (`breakpoint`/`load_breakpoint` in `Experiment()`, `save_state_breakpoint`/`load_state_breakpoint` in aggregators, strategies, secagg, etc.)
* if modified a component with versioning (config files, breakpoint, messaging protocol) then update the version following the rules in `common/utils/_versions.py`

### CODE REVIEW

**Comment by ybouilla** [comment]
Unfortunately I wont be able to test it on a macbook os. Maybe we should ask someone with such a computer in the team (Erwan, Francesco or Sergen?)

**Comment by ybouilla** [comment]
Successfully working on Ubuntu 22.04.4 LTS

**Comment by srcansiz** [comment]
Hi @here, 

I tested used Mac but it didn't work it still asks for password to connect. I removed the researcher env, reinstalled and execute `fedbiomed_run researcher start`. 

Please see the output 

```
ead the migration plan to Notebook 7 to learn about the new features and the actions to take if you are using extensions.

https://jupyter-notebook.readthedocs.io/en/latest/migrate_to_notebook7.html

Please note that updating to Notebook 7 might break some of your extensions.

[I 14:58:26.942 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.6.1
[I 14:58:26.947 NotebookApp] Serving notebooks from local directory: ....fedbiomed/notebooks
[I 14:58:26.947 NotebookApp] Jupyter Notebook 6.5.7 is running at:
[I 14:58:26.947 NotebookApp] http://localhost:8888/
[I 14:58:26.947 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 14:58:27.221 NotebookApp] 302 GET /tree (::1) 0.840000ms
```

Do I have to do something else to disable password.

**Comment by mvesin** [comment]
@srcansiz it should be working once you removed and re-created the `researcher` conda env ...

**Comment by ybouilla** [comment]
What we could do is to merge the branch but keep the issue open (still not fixed for macbook users)

**Comment by ybouilla** [comment]
> Hi @here,

I tested used Mac but it didn't work it still asks for password to connect. I removed the researcher env, reinstalled and execute fedbiomed_run researcher start.

Please see the output

ead the migration plan to Notebook 7 to learn about the new features and the actions to take if you are using extensions.

https://jupyter-notebook.readthedocs.io/en/latest/migrate_to_notebook7.html

Please note that updating to Notebook 7 might break some of your extensions.

[I 14:58:26.942 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.6.1
[I 14:58:26.947 NotebookApp] Serving notebooks from local directory: ....fedbiomed/notebooks
[I 14:58:26.947 NotebookApp] Jupyter Notebook 6.5.7 is running at:
[I 14:58:26.947 NotebookApp] http://localhost:8888/
[I 14:58:26.947 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 14:58:27.221 NotebookApp] 302 GET /tree (::1) 0.840000ms

Do I have to do something else to disable password.
image

Can you please try to remove files located in your `~/.jupyter` folder (json and python file), and check if the issue is still occurring? thanks!

**Comment by srcansiz** [comment]
> ~/.jupyter

Thank you @ybouilla, It worked after removing files in `.jupyter` directory!

**Comment by ybouilla** [comment]
For the hotfix: `CHANGELOG.md` and `constants.py` have to be modified

**Comment by ybouilla** [comment]
> For the hotfix: CHANGELOG.md and constants.py have to be modified
Done! Would you like me to do the release process? or is it ok if  i do it myself?

**Comment by mvesin** [comment]
Yes @ybouilla you can do the release of the hotfix. Thank you in advance.

**Comment by mvesin** [comment]
@ybouilla as we couldn't complete this hotfix during the past weeks, I close it and restart as a normal `feature` branch to be merged to `develop`. As next release will come soon, a hotfix is not really necessary now.

**Pull request closed without merging**
